channels:
  - conda-forge
dependencies:
  - r-base=3.9
  - r-tidyverse
  - r-tidytext
  - r-stopwords
  - r-topicmodels
  - r-reshape2
  - r-rcolorbrewer
  - r-pals
  - r-ggplot2
  - r-ggiraph
  - r-streamgraph
  - r-htmlwidgets
  - r-IRdisplay
